### ISSUE TITLE
Could not interpret optimizer identifier

### ISSUE THREAD

**Issue by porgull** [CyberZHG/keras-radam#30]
I am currently running tensorflow==2.0.0rc0

When I run:
```python
import tensorflow.keras as keras
import numpy as np
from keras_radam import RAdam

# Build toy model with RAdam optimizer
model = keras.models.Sequential()
model.add(keras.layers.Dense(input_shape=(17,), units=3))
model.compile(RAdam(), loss='mse')
```

I get this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/porgull/Desktop/Projects/rfw-keras/env/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/porgull/Desktop/Projects/rfw-keras/env/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 256, in compile
    self.optimizer = optimizers.get(optimizer)
  File "/home/porgull/Desktop/Projects/rfw-keras/env/lib/python3.7/site-packages/tensorflow_core/python/keras/optimizers.py", line 848, in get
    raise ValueError('Could not interpret optimizer identifier:', identifier)
ValueError: ('Could not interpret optimizer identifier:', <keras_radam.optimizers.RAdam object at 0x7fc9656b8610>)
```

**Comment by CyberZHG** [comment]
Add `TF_KERAS=1` to your environment variables.

**Comment by porgull** [comment]
I apologize, did not see that. Thanks.

**Comment by Astlaan** [comment]
How would you set the environment variables from python?

I tried:

os.environ['TF_KERAS'] = '1'
from keras_radam import RAdam

But I still get the same error...

I did confirm that os.environ['TF_KERAS'] indeed returns '1'.
